# -*- coding: utf-8 -*-
"""Comuni convert json to csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j69kMss4sla-RvpusQaB1HQFhkIdh8pt
"""

import geopandas as gpd
import pandas as pd
from google.colab import files  # solo in Colab

# =========================
# CARICA GEOJSON
# =========================
geojson_path = "comuni.geojson"  # caricato manualmente in Colab
gdf = gpd.read_file(geojson_path)

# =========================
# PROIETTA IN CRS METRICO PER CALCOLO CENTROIDI
# =========================
gdf = gdf.to_crs(epsg=3857)  # proiezione web mercator (metri)
gdf["centroid"] = gdf.geometry.centroid
gdf["lat"] = gdf["centroid"].y
gdf["lng"] = gdf["centroid"].x

# Riporta a EPSG:4326 (lat/lon)
gdf = gdf.to_crs(epsg=4326)
gdf["lat"] = gdf.geometry.centroid.y
gdf["lng"] = gdf.geometry.centroid.x

# =========================
# CREA CSV
# =========================
df_comuni = gdf[["name","lat","lng"]].copy()
df_comuni["nome"] = df_comuni["name"].str.lower().str.strip()

# SALVA CSV IN COLAB
csv_path = "comuni.csv"
df_comuni.to_csv(csv_path, index=False)
print(f"✅ CSV creato in Colab: {csv_path}")
print(df_comuni.head())

from google.colab import drive
import os

# Monta Google Drive
drive.mount('/content/drive')

# Crea cartella in Drive se vuoi
csv_drive_path = '/content/drive/MyDrive/comuni.csv'

# Salva il CSV
df_comuni.to_csv(csv_drive_path, index=False)
print(f"✅ CSV salvato su Google Drive: {csv_drive_path}")