# -*- coding: utf-8 -*-
"""Geometano_V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0uwVDeEJxGYtfHxpNSCIQzuonMfQzMT
"""


import streamlit as st
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
import folium
from streamlit_folium import st_folium

# CONFIG
st.set_page_config(layout="wide")

st.title("🌱 Impianti Biometano in Italia")

# CACHE (fondamentale)
@st.cache_data
def load_data():
    df = pd.read_excel("impianti.xlsx")
    return df

df = load_data()

# SIDEBAR
st.sidebar.header("🔍 Filtri")

comune_input = st.sidebar.text_input("Comune", "Milano")
raggio_km = st.sidebar.slider("Raggio (km)", 1, 100, 20)

# GEOLOCALIZZAZIONE
geolocator = Nominatim(user_agent="biometano_app")

location = geolocator.geocode(comune_input + ", Italia")

if location is None:
    st.error("Comune non trovato")
    st.stop()

lat_centro = location.latitude
lon_centro = location.longitude

# CONTROLLO COLONNE
df.columns = df.columns.str.lower()

lat_col = "latitudine"
lon_col = "longitudine"

if lat_col not in df.columns or lon_col not in df.columns:
    st.error(f"Colonne mancanti: {lat_col}, {lon_col}")
    st.write(df.columns)
    st.stop()

# DISTANZA
def calcola_distanza(row):
    return geodesic(
        (lat_centro, lon_centro),
        (row[lat_col], row[lon_col])
    ).km

df["distanza_km"] = df.apply(calcola_distanza, axis=1)

df_filtrato = df[df["distanza_km"] <= raggio_km]

# INFO
st.write(f"### Impianti trovati: {len(df_filtrato)}")
df_filtrato["descrizione"] = (
    "Comune: " + df_filtrato["comune"].astype(str) +
    "<br>Tipo: " + df_filtrato.get("tipologia", "").astype(str) +
    "<br>Distanza: " + df_filtrato["distanza_km"].round(1).astype(str) + " km"
)

df_filtrato = df_filtrato.dropna(subset=[lat_col, lon_col])
# MAPPA
import plotly.express as px

st.write("### 🗺️ Mappa interattiva")

if len(df_filtrato) > 0:

    # Colonna descrizione (modifica se serve)
    df_filtrato["descrizione"] = (
        "Comune: " + df_filtrato.get("comune", "").astype(str) +
        "<br>Distanza: " + df_filtrato["distanza_km"].round(1).astype(str) + " km"
    )

    fig = px.scatter_mapbox(
        df_filtrato,
        lat=lat_col,
        lon=lon_col,
        hover_name="comune" if "comune" in df_filtrato.columns else None,
        hover_data={
            "distanza_km": True
        },
        zoom=7,
        height=600
    )

    fig.update_layout(
        mapbox_style="open-street-map",
        margin={"r":0,"t":0,"l":0,"b":0}
    )

    st.plotly_chart(fig, use_container_width=True)

else:
    st.warning("Nessun impianto trovato")
# TABELLA
st.write("### 📊 Tabella")
st.dataframe(df_filtrato, height=400)
