# -*- coding: utf-8 -*-
"""Geometano_V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0uwVDeEJxGYtfHxpNSCIQzuonMfQzMT
"""

!pip install streamlit folium streamlit-folium geopy openpyxl

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from geopy.geocoders import Nominatim
# from geopy.distance import geodesic
# import folium
# from streamlit_folium import st_folium
# 
# # CONFIG
# st.set_page_config(layout="wide")
# 
# st.title("🌱 Impianti Biometano in Italia")
# 
# # CACHE (fondamentale)
# @st.cache_data
# def load_data():
#     df = pd.read_excel("impianti.xlsx")
#     return df
# 
# df = load_data()
# 
# # SIDEBAR
# st.sidebar.header("🔍 Filtri")
# 
# comune_input = st.sidebar.text_input("Comune", "Milano")
# raggio_km = st.sidebar.slider("Raggio (km)", 1, 100, 20)
# 
# # GEOLOCALIZZAZIONE
# geolocator = Nominatim(user_agent="biometano_app")
# 
# location = geolocator.geocode(comune_input + ", Italia")
# 
# if location is None:
#     st.error("Comune non trovato")
#     st.stop()
# 
# lat_centro = location.latitude
# lon_centro = location.longitude
# 
# # CONTROLLO COLONNE (IMPORTANTE)
# df.columns = df.columns.str.lower()
# 
# # CAMBIA QUESTI NOMI SE SERVE
# lat_col = "latitudine"
# lon_col = "longitudine"
# 
# if lat_col not in df.columns or lon_col not in df.columns:
#     st.error(f"Colonne mancanti: {lat_col}, {lon_col}")
#     st.write(df.columns)
#     st.stop()
# 
# # DISTANZA
# def calcola_distanza(row):
#     return geodesic(
#         (lat_centro, lon_centro),
#         (row[lat_col], row[lon_col])
#     ).km
# 
# df["distanza_km"] = df.apply(calcola_distanza, axis=1)
# 
# df_filtrato = df[df["distanza_km"] <= raggio_km]
# 
# # INFO
# st.write(f"### Impianti trovati: {len(df_filtrato)}")
# 
# # MAPPA
# mappa = folium.Map(location=[lat_centro, lon_centro], zoom_start=9)
# 
# for _, row in df_filtrato.iterrows():
#     folium.Marker(
#         [row[lat_col], row[lon_col]],
#         popup=str(row.get("comune", "Impianto"))
#     ).add_to(mappa)
# 
# st.write("### 🗺️ Mappa")
# st_folium(mappa, height=500)
# 
# # TABELLA
# st.write("### 📊 Tabella")
# st.dataframe(df_filtrato, height=400)

!streamlit run app.py &>/dev/null &

!curl ipv4.icanhazip.com