# -*- coding: utf-8 -*-
"""Impianti geocodificati

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaUwea-8bu38IZ5MuTnChLEaB9qumkfV
"""

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

# -*- coding: utf-8 -*-

import pandas as pd
import time
import os
import pickle
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

# =========================
# CONFIG
# =========================
MODE = "colab"  # 👉 cambia in "streamlit" quando vai su Streamlit
FILE_INPUT = "impianti.xlsx"
FILE_OUTPUT = "impianti_geocodificati.xlsx"
CACHE_FILE = "geocode_cache.pkl"

# =========================
# CARICAMENTO DATI
# =========================
if os.path.exists(FILE_OUTPUT):
    print("📄 Carico file geocodificato esistente...")
    df = pd.read_excel(FILE_OUTPUT)
else:
    print("📄 Carico file input originale...")
    df = pd.read_excel(FILE_INPUT)

df.columns = df.columns.str.strip().str.lower()

# controllo colonne necessarie
required_cols = ["comune", "provincia", "regione"]
for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"❌ Colonna mancante: {col}")

df["comune"] = df["comune"].astype(str).str.strip()
df["provincia"] = df["provincia"].astype(str).str.strip()
df["regione"] = df["regione"].astype(str).str.strip()

# =========================
# CREA QUERY GEOCODING
# =========================
def crea_query(row):
    return f"{row['comune']}, {row['provincia']}, {row['regione']}, Italia"

df["query"] = df.apply(crea_query, axis=1)

# =========================
# SETUP GEOCODER + CACHE
# =========================
geolocator = Nominatim(user_agent="biometano_pro")

# carico cache se esiste
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "rb") as f:
        cache = pickle.load(f)
else:
    cache = {}

# funzione geocoding con timeout
def geocode(query):
    try:
        location = geolocator.geocode(query, timeout=10)
        if location:
            return location.latitude, location.longitude
    except GeocoderTimedOut:
        return None, None
    return None, None

# =========================
# RIGHE DA GEOCODIFICARE
# =========================
df["latitudine"] = df.get("latitudine", None)
df["longitudine"] = df.get("longitudine", None)

rows_to_geocode = df[df["latitudine"].isna() | df["longitudine"].isna()]
print(f"🔎 Geocoding righe mancanti: {len(rows_to_geocode)} su {len(df)}")

# =========================
# CICLO PRINCIPALE
# =========================
for i, row in rows_to_geocode.iterrows():
    query = row["query"]

    if query in cache:
        lat, lon = cache[query]
    else:
        lat, lon = geocode(query)
        if lat is None:
            # fallback: solo comune + Italia
            lat, lon = geocode(f"{row['comune']}, Italia")
        cache[query] = (lat, lon)
        time.sleep(1.2)  # evitare rate limit di Nominatim

    df.at[i, "latitudine"] = lat
    df.at[i, "longitudine"] = lon

    print(f"{i+1}/{len(df)} → {query} → {lat}, {lon}")

    # salvataggio periodico
    if i % 20 == 0:
        df.to_excel(FILE_OUTPUT, index=False)
        with open(CACHE_FILE, "wb") as f:
            pickle.dump(cache, f)
        print("💾 Salvataggio intermedio completato")

# =========================
# SALVATAGGIO FINALE
# =========================
df.to_excel(FILE_OUTPUT, index=False)
with open(CACHE_FILE, "wb") as f:
    pickle.dump(cache, f)

print("✅ FILE GENERATO:", FILE_OUTPUT)
print("✅ CACHE AGGIORNATA:", CACHE_FILE)

from google.colab import files
files.download("impianti_geocodificati.xlsx")